version: '3.7'
services:
  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - ./:/usr/src/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    depends_on:
      - php-fpm
  php-fpm:
    build: ./
    entrypoint: ["/usr/src/app/docker/entrypoint.sh"]
    command: ["php-fpm"]
    volumes:
      - ./:/usr/src/app
